INSERT into Players (id, name) values (1, 'Джокович');
INSERT into Players (id, name) values (2, 'Федерер');
INSERT into Players (id, name) values (3, 'Надаль');
INSERT into Players (id, name) values (4, 'Агасси');
INSERT into Players (id, name) values (5, 'Сампрас');
INSERT into Players (id, name) values (6, 'Сафин');
INSERT into Players (id, name) values (7, 'Борг');
INSERT into Players (id, name) values (8, 'Медведев');
INSERT into Players (id, name) values (9, 'Кафельников');
INSERT into Players (id, name) values (10, 'Беккер');
ALTER SEQUENCE player_seq RESTART WITH 11;

INSERT into Matches (id, player1, player2, winner) values (1, 1, 10, 10 );
INSERT into Matches (id, player1, player2, winner) values (2, 2, 9, 2 );
INSERT into Matches (id, player1, player2, winner) values (3, 3, 8, 8 );
INSERT into Matches (id, player1, player2, winner) values (4, 4, 7, 4 );
INSERT into Matches (id, player1, player2, winner) values (5, 5, 6, 6 );
INSERT into Matches (id, player1, player2, winner) values (6, 6, 5, 5 );
INSERT into Matches (id, player1, player2, winner) values (7, 7, 4, 4 );
INSERT into Matches (id, player1, player2, winner) values (8, 8, 3, 3 );
INSERT into Matches (id, player1, player2, winner) values (9, 9, 2, 2 );
INSERT into Matches (id, player1, player2, winner) values (10, 10, 1, 1 );
INSERT into Matches (id, player1, player2, winner) values (11, 10, 2, 10 );
INSERT into Matches (id, player1, player2, winner) values (12, 10, 3, 3 );
INSERT into Matches (id, player1, player2, winner) values (13, 10, 4, 10 );
INSERT into Matches (id, player1, player2, winner) values (14, 10, 5, 5 );
INSERT into Matches (id, player1, player2, winner) values (15, 10, 6, 10 );
INSERT into Matches (id, player1, player2, winner) values (16, 9, 4, 4 );
INSERT into Matches (id, player1, player2, winner) values (17, 8, 5, 5 );
ALTER SEQUENCE match_seq RESTART WITH 18;
